### ISSUE TITLE
Is there a way to refresh the layout?

### ISSUE THREAD

**Issue by liamtarpey** [homerjam/angular-gridify#4]
Is there a way to refresh the layout on click? I have a 'load more' button that appends more items to the array i'm looping through with ng-repeat. Unfortunately when the next lot of items load, they don't get the layout properties.

**Comment by homerjam** [comment]
This directive would basically replace ng-repeat in most situations. You can specify the collection to watch using the `watch` option, when this has items appended it would trigger a reflow.

You might want to also checkout `homerjam/angular-gridflex` as an alternative - that tends to be better maintained ; )

**Comment by liamtarpey** [comment]
Brilliant! I was using the watch option but I clearly wasn't doing it properly :P 

Will check out grid-flex as well. Thanks James - amazing work.
