### ISSUE TITLE
Responsive issue: changing perRow value

### ISSUE THREAD

**Issue by liamtarpey** [homerjam/angular-gridify#5]
Hi James, 

Is there a way for the grid to watch the perRow? I've tried something like the below, but not having much luck.

Ideally I want 3 items per row on any screens over 767px and just one item on any smaller devices.

``` html
perRow: itemsPerRow
```

``` javascript
$scope.itemsPerRow = 3;

window.onresize = function() {
    if (window.innerWidth >= 767) {
           $scope.$apply(function() {
               $scope.itemsPerRow = 3;
        });
    } else {
        $scope.$apply(function() {
                 $scope.itemsPerRow = 1;
        });
    }
}
```

**Comment by homerjam** [comment]
Hi Liam,

I've updated the readme with an example of this

**Comment by liamtarpey** [comment]
Excellent, works great. Thanks again James :)
