### ISSUE TITLE
Splicing items from array - watch scope changes

### ISSUE THREAD

**Issue by liamtarpey** [homerjam/angular-gridify#6]
Hey James, 

Hopefully the last question... :) 

I have a 'load more' function that simply pushes new objects to my $scope.cards array which works fine. I'm watching $scope.cards and it refreshes the grid accordingly. 

However, I also have a 'delete' function that splices objects from the array but the grid doesn't refresh even though it's watching for changes to $scope.cards. I just end up with a blank space on my screen.

Any ideas why this would be happening?

Thanks.

**Comment by homerjam** [comment]
Is the delete function called within the digest cycle?

You may need to manually trigger it otherwise.

``` js
delete(x);

$scope.$apply(); // manually trigger digest (hacky)

// or (better)

$timeout(function(){ // automatically (and safely) triggers digest
    delete(x);
});
```

**Comment by liamtarpey** [comment]
Yes, definitely being called in the digest cycle. The first options gives me the 'digest already in progress console error'. Second one doesn't refresh the grid either, even if I offset the timeout by a second or two.

**Comment by homerjam** [comment]
Can you test the latest commit please?

**Comment by liamtarpey** [comment]
I think that's broken a few things, the grid items load at 100% on page load (needs a browser resize to trigger the refresh). 

However, the grid does refresh after 'delete' but unfortunately at 100% again.

Here's a screenshot, I removed the middle item (in the row with the white space) and the third item jumped to the next row at 100% width.

Thanks James.

![screen shot 2015-10-14 at 11 35 09](https://cloud.githubusercontent.com/assets/4904859/10481360/fd6bc90c-7267-11e5-8e7f-c69b968bacbe.png)

**Comment by homerjam** [comment]
I've updated the example and it's working - maybe look at how you're removing items from the array to solve this

**Comment by liamtarpey** [comment]
Hmm interesting, I'm doing it in a very similar way to the example. 

Will look into it more though on my end. Thanks a lot!

**Comment by liamtarpey** [comment]
Still having issues with this - removing the item in the exact same way that you are. Is there a method to force trigger a 're-layout' of the grid?

**Comment by homerjam** [comment]
There isn't at the moment - you could try

```
angular.element($window).trigger('resize')
```

**Comment by liamtarpey** [comment]
No luck with that but I've come up with this based on your above suggestion... (a bit hacky, but it works!)

Controller:

``` javascript
$scope.cards.splice(index, 1);
$timeout(function() {
    $rootScope.$broadcast('reLayout');
}, 1000);
```

Directive:

``` javascript
$rootScope.$on('reLayout', _init);
```

I had to use the 1000ms timeout as `_init` runs immediately after the splice (watching the cards scope) but when setting the `targets` variable in the directive, it still picks up the initial amount of items we had before the splice happened.

Looking likely it's a performance/watch issue with ng-repeat? Can't trigger a $scope.$apply of course... :-1: 

Will let you know if I come up with a better solution.

**Comment by homerjam** [comment]
@liamtarpey have you had a chance to try the new version? I've tried to improve collection watching and have added a listener so you can do the following to force a relayout:

``` js
$scope.$broadcast('gridify:init');
```

**Comment by liamtarpey** [comment]
Sorry for the delay @homerjam.

Yes - no problems at all with removing cards now. Don't actually need to use the `gridify:init` broadcast but it might come in handy at some point. Thanks for adding it in!
