### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by cwhite92** [homerjam/angular-gridify#7]
I'm wondering how welcome a PR would be for removing the jQuery dependency for this directive?

When I first tried using it, I didn't realise I needed jQuery (as it doesn't seem to be mentioned anywhere) and was frustrated with it not working. From quickly glancing over the source, there doesn't seem to be any substantial code that relies on jQuery that couldn't be done in vanilla JS.

Would you accept a PR? This directive is exactly what I'm looking for, but now I have another ~80KB library that I didn't need before.

**Comment by cwhite92** [comment]
Actually, looking into the source more, I can't see anything which would rely on the entire jQuery library being loaded, because it all uses `angular.element` which should be using jqLite. Also on the example page, jQuery isn't loaded.

In that case, I'm really confused as to why the directive wasn't working for me without loading the entire jQuery library. It seemed to not apply any of the computing css rules here: https://github.com/homerjam/angular-gridify/blob/master/angular-gridify.js#L191

I'll have to have another look when I'm back at home, but for now this might just be a red herring. Sorry :)

**Comment by liamtarpey** [comment]
I have the exact same issue Chris. 

What's strange is that the [demo](http://homerjam.github.io/angular-gridify/) provided by the author doesn't use jQuery whatsoever. 

Trying to remove jQuery from my project now but having the same issue  of the styles not getting computed. Will investigate on my side as well. 

The only real difference I can see so far is that I'm using Angular 1.4.2 and the demo uses 1.3.0.

Very strange indeed...

**Comment by cwhite92** [comment]
Glad to see I'm not the only person with this problem, at least. The version differences are something which I'm going to investigate after I finish work, although the code that applies the computed CSS properties looks like it would work across 1.3 and 1.4 :/

**Comment by homerjam** [comment]
Guys I've just pushed a big update with different usage - please see the updated example. This should fix a lot of potential issues as the directive now handles more of the expected default behaviour - watching the collection etc.

I'd appreciate it if you could try this new version instead and give me feedback, thanks.

**Comment by liamtarpey** [comment]
Hey James, 

Thanks for the updates, really appreciate it.

However, I have two issues:
- I do not have a `ratio` property in my tile objects - as I'm retrieving data from our API, the only property I get back is `orientation` with a value of LANDSCAPE or PORTRAIT (both A5), which I was able to use with your old implementation as such: 

``` html
ng-attr-data-ratio="{{card.orientation === 'LANDSCAPE' ? '1.4142' : '0.7088'}}"
```
- My tiles display at full width, all with the following computed CSS, regardless of what `perRow` value I set:

``` css
element.style {
    display: block;
    position: relative;
    float: left;
    margin-left: 0px;
    margin-bottom: 0px;
}
```

Are you getting any of these issues on your end at all?

Thanks

**Comment by homerjam** [comment]
Hi Liam

I changed the module to read the ratio from the objects in the collection so you should add the `ratio` property in the code instead eg:

``` js
card.ratio = card.orientation == 'LANDSCAPE' ? '1.4142' : '0.7088';
```

I did this because its more performant than reading the ratio from the dom

**Comment by liamtarpey** [comment]
Thanks James, got that fixed. 

Managed to get the grid working again, but only when I re-include jQuery...

**Comment by homerjam** [comment]
Is there anyway you can post an example that replicates this? As you can see the demo doesn't need jQuery.

Is there anything coming up in the console?

**Comment by liamtarpey** [comment]
I've been logging the `css` var just before setting the css on each tile.

Without jQuery, these values get logged correctly to the console but ignored when the css gets set to the tile as the values are integers. 

Starting to get somewhere with this by converting the values to strings with "px", but I was under the impression that jqLite handled this.

Will try to post an example tomorrow if I haven't figured out my issue by then :)

**Comment by liamtarpey** [comment]
Hi again, 

I've managed to fix this on my end with jQuery removed.

Line 365:

``` javascript
wrapper.css({
  overflow: 'hidden',
   width: '100%'
});
```

Line 512 (just before `tile.css(css)`:

``` javascript
css.width = css.width + "px";
css.height = css.height + "px";
css.marginTop = css.marginTop + "px";
css.marginLeft = css.marginLeft + "px";
css.marginRight = css.marginRight + "px";
css.marginBottom = css.marginBottom + "px";
```

**Comment by cwhite92** [comment]
@liamtarpey: I've been out of action for the last couple of days so haven't tried your solution yet (I'm at work again) but I will definitely try your solution tonight. Thank you for looking into this and coming up with a solution. :)

@homerjam: assuming @liamtarpey's solution solves this issue, would you be willing to accept a PR?

**Comment by homerjam** [comment]
Should have mentioned this - I've already updated the module can you guys test please?

**Comment by homerjam** [comment]
I still find it strange though as the example isn't using jQuery and works fine. Would love to actually get to the bottom of the issue - if either of you can reproduce the problem in a plunkr/codepen/jsfiddle that'd be great

**Comment by cwhite92** [comment]
Just tested here with the latest version (0.1.1), working like a charm without jQuery!

However, I noticed the API changed and my existing markup didn't work. The markup in the readme didn't work either, in the end this worked for me:

```
<hj-gridify hj-gridify-options="{collection: photos, averageRatio: 1.5, perRow: 5, gutter: 10, maxRowHeight: 300}">
    <a href="/photo/{{ item.id }}" class="tile">
        <img ng-src="{{ item.thumb_url }}">
    </a>
</div>
```

My guess is the problem stems from the different Angular version between the demo and @liamtarpey and I's projects. Either way, it works now, and I'm very grateful for the work involved in getting it working :)

**Comment by homerjam** [comment]
@cwhite92 thanks for letting me know - I've updated the readme as suggested
